name: Student Feedback CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check HTML File
        run: test -f index.html

      - name: Check CSS File
        run: test -f style.css

      - name: Check JavaScript File
        run: test -f script.js

      - name: CI Completed
        run: echo "Student Feedback Application CI/CD successful!"
